// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Abbr: typeof import('./src/components/WeatherAbbr.vue')['default']
    Chart: typeof import('./src/components/WeatherChart.vue')['default']
    Info: typeof import('./src/components/WeatherInfo.vue')['default']
    Map: typeof import('./src/components/WeatherMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
